cam0:
  T_cam_imu:
  - [0.052123234473504004, -0.9986040017007423, 0.008556647432494846, 0.03068196938303387]
  - [-0.007305437913110946, -0.008949352761424723, -0.9999332676044184, -0.05507509632808549]
  - [0.9986139389198, 0.052057246108639654, -0.007761708746578777, -0.12407766434205443]
  - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [-0.03999018098363963, 0.0035531756082936186, -0.0006681279528559426, -0.0009677749839773924]
  distortion_model: equidistant
  intrinsics: [1057.8085759554679, 1057.8344071878955, 1031.0394456453769, 727.7604933179784]
  resolution: [2048, 1536]
  rostopic: /forwardLeft/image_raw/compressed

