cam0:
  T_cam_imu:
  - [-0.00375313,-0.99997267,0.00636997,0.132816998]
  - [0.01609339,-0.00642959,-0.99984982,0.0650370085]
  - [0.99986345,-0.00365005,0.01611708,-0.175745165]
  - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [-0.061606731291039, 0.100129900708930, 0.0, 0.0]
  distortion_model: RadTan
  intrinsics: [643.5951111267952, 642.6656126857330, 475.2215406900663, 307.4120184196884]
  resolution: [960, 600]
  rostopic: /dalsa_gray/left/image_raw

